# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OddsMLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('money_line_away', models.IntegerField()),
                ('money_line_home', models.IntegerField()),
                ('odd_type', models.CharField(max_length=25)),
                ('over_line', models.IntegerField()),
                ('point_spread_away', models.DecimalField(decimal_places=3, max_digits=5)),
                ('point_spread_away_line', models.IntegerField()),
                ('point_spread_home', models.DecimalField(decimal_places=3, max_digits=5)),
                ('point_spread_home_line', models.IntegerField()),
                ('total_number', models.DecimalField(decimal_places=3, max_digits=5)),
                ('under_line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id_key', models.CharField(max_length=255)),
                ('away_pitcher', models.CharField(max_length=25)),
                ('away_rot', models.IntegerField()),
                ('away_team', models.CharField(max_length=25)),
                ('home_pitcher', models.CharField(max_length=25)),
                ('home_rot', models.IntegerField()),
                ('home_team', models.CharField(max_length=25)),
                ('match_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='oddsmlb',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='Odds.ScheduleMLB'),
        ),
    ]
