# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Odds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_line_away', models.IntegerField()),
                ('money_line_home', models.IntegerField()),
                ('point_spread_away_line', models.IntegerField()),
                ('point_spread_home_line', models.IntegerField()),
                ('over_line', models.IntegerField()),
                ('under_line', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_odds', to='Odds.OddsMLB')),
                ('schedule_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Odds.ScheduleMLB')),
                ('user', models.ForeignKey(default='user_bets', on_delete=django.db.models.deletion.CASCADE, related_name='user_bets', to='Odds.User')),
            ],
        ),
    ]
