# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Odds', '0002_betslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
