# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Odds', '0003_auto_20170917_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Odds.User'),
        ),
    ]
