# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Odds', '0007_auto_20170926_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='schedule_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Odds.ScheduleMLB'),
        ),
    ]
